#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/../../etc/vmm/kvm/kvmrc
source $(dirname $0)/../../scripts_common.sh

DOMAIN=$1

DOMAIN_LOCATION=$(dirname $DOMAIN)
mkdir -p $DOMAIN_LOCATION
cat > $DOMAIN

DATA=`virsh --connect $LIBVIRT_URI create $DOMAIN`

if [ "x$?" = "x0" ]; then

    DOMAIN=$(echo $DATA | sed 's/Domain //' | sed 's/ created from .*$//')

    for SNAPSHOT_MD_XML in $(ls ${DOMAIN_LOCATION}/snap-*.xml 2>/dev/null); do

        # query UUID only once
        UUID=${UUID:-$(virsh --connect $LIBVIRT_URI dominfo $DOMAIN | grep UUID: | awk '{print $2}')}

        # replace uuid in the snapshot metadata xml
        sed -i "s%<uuid>[[:alnum:]-]*</uuid>%<uuid>$UUID</uuid>%" $SNAPSHOT_MD_XML

        # redefine the snapshot using the xml metadata file
        virsh --connect $LIBVIRT_URI snapshot-create $DOMAIN $SNAPSHOT_MD_XML --redefine
    done
    echo $DOMAIN

else
    error_message "Could not create domain from $DOMAIN"
    exit -1
fi
